version: '3.0'

services:
  nc-database:
    image: mariadb:10.3
    environment:
      - "MYSQL_ROOT_PASSWORD"
    env_file:
      - ../nextcloud/database.env
    restart: unless-stopped
    volumes:
      - "${DOCKER_DATA_BASEDIR:-/srv/docker}/nextcloud/mysql/data:/var/lib/mysql"
      - "${DOCKER_DATA_BASEDIR:-/srv/docker}/nextcloud/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf:ro"
    networks:
      - nextcloud

  nc-redis:
    image: redis:5.0-alpine
    restart: unless-stopped
    networks:
      - nextcloud

  nc:
    image: nextcloud:16.0
    depends_on:
      - nginx-letsencrypt
      - nginx-proxy
      - nc-database
      - nc-redis
    environment:
      - "MYSQL_HOST=nc-database"
      - "REDIS_HOST=nc-redis"
      - "VIRTUAL_HOST=cloud.nightspotlight.me"
      - "LETSENCRYPT_EMAIL=nightspotlight@gmail.com"
      - "LETSENCRYPT_HOST=cloud.nightspotlight.me"
    env_file:
      - ../nextcloud/database.env
    restart: unless-stopped
    volumes:
      - "${DOCKER_DATA_BASEDIR:-/srv/docker}/nextcloud/nextcloud-server/custom_apps:/var/www/html/custom_apps"
      - "${DOCKER_DATA_BASEDIR:-/srv/docker}/nextcloud/nextcloud-server/config:/var/www/html/config"
      - "${DOCKER_DATA_BASEDIR:-/srv/docker}/nextcloud/nextcloud-server/data:/var/www/html/data"
      - "nextcloud-html:/var/www/html"
    networks:
      - nginx-proxy
      - nextcloud

  nc-cron:
    image: nextcloud:16.0
    restart: unless-stopped
    volumes:
      - "${DOCKER_DATA_BASEDIR:-/srv/docker}/nextcloud/nextcloud-server/custom_apps:/var/www/html/custom_apps"
      - "${DOCKER_DATA_BASEDIR:-/srv/docker}/nextcloud/nextcloud-server/config:/var/www/html/config"
      - "${DOCKER_DATA_BASEDIR:-/srv/docker}/nextcloud/nextcloud-server/data:/var/www/html/data"
      - "nextcloud-html:/var/www/html"
    entrypoint: /cron.sh
    depends_on:
      - nc-database
      - nc-redis
    networks:
      - nextcloud

networks:
  nextcloud:
    driver: bridge

volumes:
  nextcloud-html:
    driver: local
